language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.1

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    MALLOC_ARENA_MAX=2
    GRADLE_OPTS=-Xmx2048m -Dorg.gradle.parallel=false

addons:
  apt:
    packages:
      - tar
      - gzip
      - patch

before_install:
  - openssl aes-256-cbc -K $encrypted_9b8203f9524d_key -iv $encrypted_9b8203f9524d_iv -in travis/configs/twidere_private_config.tar.gz.enc -out travis/configs/twidere_private_config.tar.gz -d

install:
  # Extracts build configs into source tree
  - tar zxf travis/configs/twidere_private_config.tar.gz

before_script:
  # Validate if patches work
  - patch --dry-run -d twidere < twidere/patches/remove_closed_source_dependencies.patch

script: ./gradlew build --no-daemon --stacktrace

deploy:
  provider: releases
  api_key:
    secure: WKtKwda3hegqO9QVujdonNoL2ESJUR80WHNq/13wDsbCABo/GNnuqHNYZmml3wAifEKKeCEYfNZRUuHQ8eHs54Lj5BlGRX5i+1LrGhhgnVFQgmrhIv4RJuVQ663kDEh+Jwo4vowJ2mxNDvLvOhfZwxjULPDiknqy6u5PyW3id5M=
  file_glob: true
  file: '**/*-release.apk'
  on:
    repo: TwidereProject/Twidere-Android
    tags: true